language: scala
jdk:
- oraclejdk8
env:
  global:
  - secure: ol8YVL8vEBW6rOg/myUFz7/CXbOxQZoH8TRkdjfNLYGdyCSEKoHmLxEqIt8uzsmRkq8lAb5oTXxQ8T1z27f8UFFD5xokZg5zb01lAsbxo5P/Veg7VsMGa33vNZWW/ne1Tu3FLFQa3/kY/CM/qnmo1uTKXn/qwUcuamZbGMGLXjYwGeP8H3Ovan9JGqNf/egSROExhaPQntfQVS5KlHHY8IRXhTfP2YXrzqD//3il0bk7Q+AYiEBcNr0TFWgQd7kz1hExEIbJhgiyLQgQRv3FDQn3WQHVSWPxN46q0giHl+Ep/CL0paG9a7IxLxIq8EbGZz5aQj/kqlRVPnWAj4BJtYJ5DE6A+PbRPvPm3pUM+B7BPba26K+VfvISiHFJSmvlLW/b3ZFrOSlR6T85QYllz5MGX245USOMu4BSmSdTg+KpCpewMkif3yNveoAwoH0Q+yT/Rcxm1VmEUlakB5e4M9eYW9LvZsKM0m1GPoGDd6HoB5nc/s5ytMUyFhHJiYxACoBDgD8ttJq6vjFMwv8C+D1zcaJiruqghXxPZc/m3cxwu0AcZtJrpnaeelZHhwWXMurKMm4fN4+u/J965mwLVm6b5tFEOeVd1OPohuLvt8uIqxb2WeaBqnTCH44T7WTtf6dN7FF6HEqjs7DxZY+29S3A1ZDvDw2tYT8xcuNCK40=
  - secure: gpb1m1bwvXfimY7kosFBQnwL8Sag9Z/XHcBE6L/eNKbw4adXCzfDanUMWlIhlm7gP3rBHo5Fn/y12RC+r71TSGHg5m3R70BkkqKmXkEWBWtTdBP5dLSI/6KqGLkaSFvE4pRHhud9gI9r3qtvkkbiop0Uc/0YyoJTUv4q3fNQ4DNvxXVSeI5+B03cxIk00hPgVxhNw3j9dScEjd5xpQaR2vrMKeAcQF3AUJOaxj+lSCZxmmWXYzDlPTo/n0YpBYzKabq76MVVyTdb8Cn3AALFjLWNFhNpWfUf0+mF10nZRT+NiRT7Bz0fqG1CL+Pb3XBgUShbBKhEaTnoBn9HU1e+WVSIDh197vVAtW/isgg1xf+lRe8V1cKkky8FqxWw7gj3OG7FXVJbO/VG3YM2+eUWYlJ+jDCFy3oDiGh0fpfd6BItbhPJW0owqO5rpvIxKb6EnXkzF+75Nbbr7XW8anNQ7+sExGQXpRGPCRzs0A9mxSf54S5cx+Z+xJOo2UHTWS6AcdZm6SovyBwNQUHbQNUVA0eQsesotE4KRsiqqtp2IhQpBJiJ8GT5JNB33HjTYyba94APYyC/V1Xg8ouHyYe+bEawboK0KYCHRC40BRCZCZhnj87Wt2qgiM2ePASU0G1X+KoxND2LJSuhzbHODcS9bBQmLqBjXNBzXPqHkyfOtUA=
before_script:
- mkdir ~/.bintray
- touch ~/.bintray/.credentials
- echo 'realm = Bintray API Realm' >> ~/.bintray/.credentials
- echo 'host = api.bintray.com' >> ~/.bintray/.credentials
- echo "user = $BT_USER" >> ~/.bintray/.credentials
- echo "password = $BT_KEY" >> ~/.bintray/.credentials
script:
- sbt test && sbt publish
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
